posproject/posapp/urls.py
from django.urls import path
from .views import *
from . import *
app_name = 'posapp'



urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('home/',HomeView.as_view(),name = 'home'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    #supplier
    path('supplier/list/', SupplierListView.as_view(), name='supplierlist'),
    path('supplier/create/', SupplierCreateView.as_view(), name='studentcreate'),
    path('supplier/update/<int:pk>/',
         SupplierUpdateView.as_view(), name='supplierupdate'),
    path('supplier/delete/<int:pk>/',
         SupplierdeleteView.as_view(), name='supplierdelete'),
    
    #customer
    path('customer/list/', CustomerListView.as_view(), name='customerlist'),
    path('customer/create/', CustomerCreateView.as_view(), name='customercreate'),
    path('customer/update/<int:pk>/',
         CustomerUpdateView.as_view(), name='customerupdate'),
    path('customer/delete/<int:pk>/',
         CustomerdeleteView.as_view(), name='customerdelete'),
     
     #products
     path('product/list/', ProductListView.as_view(), name='productslist'),

     path('product/create/',ProductCreateView.as_view(),name = 'productcreate'),

     path('product/update/<int:pk>/',
         ProductUpdateView.as_view(), name='productupdate'),

     
     path('product/delete/<int:pk>/',
         ProductdeleteView.as_view(), name='productdelete'),
    

     #################### TODO:crud of products ##########
     #sales list
     path('sales/list/', SalesListView.as_view(), name='saleslist'),


     path('sales/create/',views.CreateInvoiceView,name = 'salescreate'),

     path('billing/order', views.orderBill, name='order'),

     path('bill/<int:pk>', views.BillGeneration, name='bill'),

     #chart js
     path('chart/',ChartView.as_view(),name='chart'),










    

    
    







]

posproject/posproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posapp.urls")),
  
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

posproject/templates/admintemplates/adminbase.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>pos</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Modern Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="{% static 'adminstatic/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="{% static 'adminstatic/css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<!-- <link href="{% static 'adminstatic/css/lines.css' %}" rel='stylesheet' type='text/css' /> -->
<!-- <link href="{% static 'adminstatic/css/font-awesome.css' %}" rel="stylesheet">  -->
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- jQuery -->
<script src="{% static 'adminstatic/js/jquery.min.js' %}"></script>
<!----webfonts--->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
<!---//webfonts--->  
<!-- Nav CSS -->
<link href="{% static 'adminstatic/css/custom.css' %}" rel="stylesheet">
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'adminstatic/js/metisMenu.min.js' %}"></script>
<script src="{% static 'adminstatic/js/custom.js' %}"></script>
<!-- Graph JavaScript -->

</head>
<body>
<div id="wrapper">
     <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;background-color:#33ff33">
            <div class="navbar-header">
                
                <a class="navbar-brand" href="{% url 'posapp:home' %}">MyPos</a>
                <!-- <p class="navbar-brand" style="text-align: center;">{% now "jS F Y" %}</p> -->

                <!-- <p class="navbar-brand" style="text-align: center;">{% now "jS F Y" %}</p> -->

            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-nav navbar-right">
				<!-- <p>Welcome : {{ request.user.username }}</p> -->
				<li class="dropdown">
                        
	        		<a href="#" style="color: white;" data-toggle="dropdown"><img src="{% static 'adminstatic/images/3.png' %}" width="40px;" height="40px;">Welcome : {{ request.user.username }}</a>
	        		<ul class="dropdown-menu">
						<!-- <li class="m_2"><a href="#"><i class="fa fa-user"></i> Profile</a></li>
						<li class="m_2"><a href="#"><i class="fa fa-wrench"></i> Settings</a></li>
						<li class="m_2"><a href="#"><i class="fa fa-usd"></i> Payments <span class="label label-default">42</span></a></li>
						<li class="m_2"><a href="#"><i class="fa fa-file"></i> Projects <span class="label label-primary">42</span></a></li>
						<li class="divider"></li>
						<li class="m_2"><a href="#"><i class="fa fa-shield"></i> Lock Profile</a></li> -->
						<li class="m_2"><a href="{% url 'posapp:logout' %}"><i class="fa fa-lock"></i> Logout</a></li>	
	        		</ul>
	      		</li>
			</ul>
			
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{% url 'posapp:home' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'posapp:supplierlist' %}"><i class="fa fa-book nav_icon"></i>suppliers</a>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="{% url 'posapp:customerlist' %}"><i class="fa fa-users nav_icon"></i>customers</a>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="{% url 'posapp:productslist' %}"><i class="fa fa-flask nav_icon"></i>products</a>
                        </li>
                         <li>
                            <a href="{% url 'posapp:saleslist' %}"><i class="fa fa-list-alt nav_icon"></i>sales</a>
                        </li>
                        <li>
                            <a href="{% url 'posapp:chart' %}"><i class="fa fa-list-alt nav_icon"></i>Reports</a>
                        </li>
                        <li>
                            <!-- <a href="#"><i class="fa fa-sitemap fa-fw nav_icon"></i>Css<span class="fa arrow"></span></a> -->
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="media.html">Media</a>
                                </li>
                                <li>
                                    <a href="login.html">Login</a>
                                </li>
                            </ul>

                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- {% block banner %}{% endblock %} -->
        <div id="page-wrapper">
        <div class="graphs">

        {% block content %}
        {% endblock %}

		
		</div>
       </div>
      <!-- /#page-wrapper -->
   </div>
    <!-- /#wrapper -->
    <!-- Bootstrap Core JavaScript -->
    <!-- <script src="{% static 'adminstatic/js/bootstrap.min.js' %}"></script> -->
</body>
</html>

posproject/templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <style>
        .card{
            background-color: #191919;
            margin: 10px;
            text-align: center;
            height: 150px;
            padding: 20px;
            }
        .text-default{
            color: white;
        }
        .card a {
                text-decoration: none;
                color: white;
        }
    </style>
</head> 
<body>      
    <div style="margin: 0px;" class="row">
        <div class="col-md-4">    
            <div class="card">
                    <a>
                        <div class="card-body">
                                        <i class="fa fa-user fa-4x" style="color:#fff"></i>
                                        <p><a href="{% url 'posapp:supplierlist' %}">Suppliers</a></p>
                        </div>
                   </a>
            </div>
            
        </div>

        <div class="col-md-4">
                <div class="card">
                        <i class="fa fa-tasks fa-4x" style="color:#fff"></i>
                        <div class="card-body">
                        <p><a href="{% url 'posapp:customerlist' %}">Customers</a></p>
                        </div>
                </div>
                
        </div>

        <div class="col-md-4">
                <div class="card">
                        <i class="fa fa-shopping-cart fa-4x" style="color:#fff"></i>
                        <div class="card-body">
                        <p><a href="{% url 'posapp:productslist' %}">Products</a></p>
                        </div>
                </div>
                
        </div>

        <div class="col-md-4">
                <div class="card">
                        <i class="fa fa-dollar fa-4x" style="color:#fff"></i>
                        <div class="card-body">
                        <p><a href="{% url 'posapp:saleslist' %}">Sales</a></p>
                        </div>
                </div>
                
        </div>

        <div class="col-md-4">
                <div class="card">
                        <i class="fa fa-th fa-4x" style="color:#fff"></i>
                        <div class="card-body">
                        <p><a href="{% url 'posapp:chart' %}">Reports</a></p>
                        </div>
                </div>
                
        </div>





    </div>


</body>     
</html>    
{% endblock %}
<div class="card text-center">
  <div class="card-header">
    image 
  </div>
  <div class="card-body">
    form
  </div>
</div>