posproject/posapp/urls.py
from django.urls import path
from .views import *
from . import *
app_name = 'posapp'



urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('home/',HomeView.as_view(),name = 'home'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    #supplier
    path('supplier/list/', SupplierListView.as_view(), name='supplierlist'),
    path('supplier/create/', SupplierCreateView.as_view(), name='studentcreate'),
    path('supplier/update/<int:pk>/',
         SupplierUpdateView.as_view(), name='supplierupdate'),
    path('supplier/delete/<int:pk>/',
         SupplierdeleteView.as_view(), name='supplierdelete'),
    
    #customer
    path('customer/list/', CustomerListView.as_view(), name='customerlist'),
    path('customer/create/', CustomerCreateView.as_view(), name='customercreate'),
    path('customer/update/<int:pk>/',
         CustomerUpdateView.as_view(), name='customerupdate'),
    path('customer/delete/<int:pk>/',
         CustomerdeleteView.as_view(), name='customerdelete'),
     
     #products
     path('product/list/', ProductListView.as_view(), name='productslist'),

     path('product/create/',ProductCreateView.as_view(),name = 'productcreate'),

     path('product/update/<int:pk>/',
         ProductUpdateView.as_view(), name='productupdate'),

     
     path('product/delete/<int:pk>/',
         ProductdeleteView.as_view(), name='productdelete'),
    

     #################### TODO:crud of products ##########
     #sales list
     path('sales/list/', SalesListView.as_view(), name='saleslist'),


     path('sales/create/',views.CreateInvoiceView,name = 'salescreate'),

     path('billing/order', views.orderBill, name='order'),

     path('bill/<int:pk>', views.BillGeneration, name='bill'),

     #chart js
     path('chart/',ChartView.as_view(),name='chart'),










    

    
    







]

posproject/posproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posapp.urls")),
  
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

posproject/templates/sales/customerform.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<head>
        <style>
            .card{
                background-color:burlywood;
                width: 100%;
                margin-left:407px;
                height: 150px;
                padding: 20px;
                }
            .text-default{
                color: white;
            }
            .card a {
                    text-decoration: none;
                    color: white;
            }
           
        </style>
    </head> 
<body>      
    

<h3 class="text-center">Customer</h3>

 <body style="margin: 0px;" class="row">
    <div class="col-md-4">    
        <div class="card">
                <div class="card-body">
                <button class="btn btn-danger"  style="text-align: center;margin: -1px 5px 17px 80px;font-size: 15px;border-radius: 10px;"><a href="{% url 'posapp:customercreate' %}">Add customer</a></button>

                    <form action="#" method="post"> 
                        {% csrf_token %}
                            <div class="input-group mb-3" style="margin-left: 30px;">
                              <div class="input-group-prepend">
                                <!-- <span class="input-group-text" id="basic-addon1">Enter Customer name: </span> -->
                              </div>

                                <!-- <p>{{ salesform.customer }}</p>   -->
                                <select name="dropdown" class="btn btn-success btn-md">
                                    <option selected="selected" disabled>Select a Customer</option>
                                    {% for cus in  customer %}
                                        <option>{{ cus.customer  }}</option>
                                    {% endfor %}
                                    
                                </select>
                                <input  type="submit" value="Go &raquo;" style="border-radius: 18%;background-color: cornsilk;">
                                <!-- <input class="btn btn-default"  name="ram" placeholder="customer name"/> -->
                                <!-- <button class="btn btn-primary type="submit" style="border-radius: 20%;">Go &raquo;</button> -->

                            </div>
                            
                    </form>
                
                </div>
                
            
        </div>


        
    </div>


</body>
{% endblock %}

posproject/templates/sales/orderbill.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}

<br>
<br>
<br>
<head>
        <style>
            .card{
                background-color:paleturquoise;
                width: 100%;
                margin-left:415px;
                height: 150px;
                padding: 20px;
                }
            .text-default{
                color: white;
            }
            .card a {
                    text-decoration: none;
                    color: white;
            }
           
        </style>
    </head> 
<body>      
    

<h3 class="text-center">myBill</h3>

 <body style="margin: 0px;" class="row">
    <div class="col-md-4">    
        <div class="card">
                <div class="card-body">
                    <h2 style="text-align: center;">Order Successfull!</h2>
                            <div class="input-group mb-3">
                                    <a class="btn btn-primary" href="{% url 'posapp:bill' id%}" role="button" style="margin-left: 80px;">Generate bill</a>

                            </div>


                </div>
        </div>
        
    </div>

<!-- <br><br>
<div class="d-flex justify-content-center">
        <div class="alert alert-success" role="alert">
          <h2 class="alert-heading">Order Successfull</h2>
          <a class="btn btn-primary" href="#" role="button">Generate bill</a>
        </div>
       
</div> -->
<!-- <h3>order successfully created</h3> -->

{% endblock %}

posproject/templates/sales/salescreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-md-12 table-responsive-sm">
            <br>
            <a href="{% url 'posapp:salescreate' %}"><button class="btn btn-lg btn-primary">Create Invoice</button></a>

            <!-- <a href="{% url 'posapp:salescreate' %}" class="btn btn-primary" style="margin-left:2px;width:195px;">Create Invoice</a> -->
            <br>           

			<table class="table table-bordered">
				<thead style="background-color: blue;color:white;text-align: center;">
					<tr class="text-dark">
						<th>S.N</th>
						<th>Customer</th>
						<th>Customer_phone</th>
                        <th>Email</th>
                        <th>product</th>
                        <th>Date</th>
                        
				
					</tr>	

				</thead>
				<tbody>
                    {% for item in order %}
                        <tr style="color: black;">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ item.order.customer.customer }}</td>
                            <td>{{ item.order.customer.customer_phone }}</td>
                            <td>{{ item.order.customer.email }}</td>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.timestamp|date:"d M Y"  }}</td>




                            <!-- <td>{{ forloop.counter }}</td>
                            <td>{{ forloop.counter }}</td> -->

                            
                            
                            
                        </tr>	


					{% endfor %}
				</tbody>
					
			</table>
		</div>
    </div>
{% endblock %}

posproject/templates/sales/test.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<style>
   .row{
     margin-left: auto;
   }
</style>
<div class="row">
    <br>
    <br>
    <br>

    <div class="col-sm-6">
      <!-- <div class="card">
        <div class="card-body">
          <h3><u>Customer</u></h3>
            {% if customer.image %}
              <img class="avatar img-thumbnail float-left img-fluid" src="{{ customer.image.url }}" style="width: 200px; margin-right: 1em;"/>
            {% endif %}
          <h3>Welcome:{{ customer.customer }}</h3>
          <h4>Location:{{ customer.address }}</h4>
        
        </div>
      </div> -->
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h2 class="card-title"><u>Customer</u></h2>
          <p class="card-text">{% if customer.image %}
            <img class="avatar img-thumbnail float-left img-fluid" src="{{ customer.image.url }}" style="width: 200px; margin-right: 1em;"/>
          {% endif %}</p>
          <a href="#" class="btn btn-lg btn-primary" style="margin-left:2px;width:195px;">{{ customer.customer }}</a>
        </div>
      </div>
      <hr>

      <!-- products  -->
      <div class="card">
        <div class="card-header">
          <h3><u>Add Products</u></h3>
        </div>
        <div class="card-body">
          {% for product in products %}
            <a href="#" onclick="addItem({{ product.id }}, '{{ product.name }}', {{ product.price }})" class="btn btn-outline-secondary">
                <img src="{{product.image.url}}" style="width: 100px; margin-left: 1em;height: 100px;">
                <br>

              <button style="margin:3px 0px 0px 7px;width: 105px;" class="btn btn-lg btn-danger">{{ product.name }}</button>

            </a>
          {% endfor %}
        </div>
      </div>

      <!-- <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h2 class="card-title"><u>Add Products</u></h2>
          {% for product in products %}
            <a href="#" onclick="addItem({{ product.id }}, '{{ product.name }}', {{ product.price }})" class="btn btn-outline-secondary">
              <img src="{{product.image.url}}" style="width: 100px; margin-left: 4px;">
              <br>

             </a>    
            <a href="#" class="btn btn-lg btn-danger" style="margin-left:25px;width:120px;">{{product.name}}</a>
          {% endfor %}
          
        </div>
      </div> -->
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
                <h3><u>Generate Bill</u></h3>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title"><strong>Order summary</strong></h4>
                </div>
                <div class="panel-body">
                  <div class="table-responsive">
                    <table class="table table-condensed">
                      <thead>
                        <tr>
                          <td><strong>Item</strong></td>
                          <td class="text-right"><strong>Price</strong></td>
                        </tr>
                      </thead>
                      <tbody id="summary-table-body">
                        <tr id="total-tr">
                          <td class="thick-line text-right"><strong>Total: </strong></td>
                          <td class="thick-line text-right"><strong>Rs.0 </strong></td></tr>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="btn-group special" role="group">
            {% csrf_token %}
            <button style="margin-left: 10px;" type="button" class="btn btn-success" onclick="postOrder('{% url 'posapp:order' %}','{{ customer.identity }}')">Bill</button>
            <button style="margin-left: 10px;" type="button" class="btn" onclick="clearAllItems()">Clear</button>
            <!-- <button type="button" class="btn btn-danger" onclick="location.href='#'">Cancel</button> -->
          </div>
        </div>
      </div>
    </div>
  </div>
  
<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

<!-- TODO:establish a relation bewtee customer and saleshistory using set-all  -->