posproject/posapp/urls.py
from django.urls import path
from .views import *
from . import *
app_name = 'posapp'



urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('home/',HomeView.as_view(),name = 'home'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    #supplier
    path('supplier/list/', SupplierListView.as_view(), name='supplierlist'),
    path('supplier/create/', SupplierCreateView.as_view(), name='studentcreate'),
    path('supplier/update/<int:pk>/',
         SupplierUpdateView.as_view(), name='supplierupdate'),
    path('supplier/delete/<int:pk>/',
         SupplierdeleteView.as_view(), name='supplierdelete'),
    
    #customer
    path('customer/list/', CustomerListView.as_view(), name='customerlist'),
    path('customer/create/', CustomerCreateView.as_view(), name='customercreate'),
    path('customer/update/<int:pk>/',
         CustomerUpdateView.as_view(), name='customerupdate'),
    path('customer/delete/<int:pk>/',
         CustomerdeleteView.as_view(), name='customerdelete'),
     
     #products
     path('product/list/', ProductListView.as_view(), name='productslist'),

     path('product/create/',ProductCreateView.as_view(),name = 'productcreate'),

     path('product/update/<int:pk>/',
         ProductUpdateView.as_view(), name='productupdate'),

     
     path('product/delete/<int:pk>/',
         ProductdeleteView.as_view(), name='productdelete'),
    

     #################### TODO:crud of products ##########
     #sales list
     path('sales/list/', SalesListView.as_view(), name='saleslist'),


     path('sales/create/',views.CreateInvoiceView,name = 'salescreate'),

     path('billing/order', views.orderBill, name='order'),

     path('bill/<int:pk>', views.BillGeneration, name='bill'),

     #chart js
     path('chart/',ChartView.as_view(),name='chart'),










    

    
    







]

posproject/posproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posapp.urls")),
  
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

posproject/templates/product/productadd.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<html>
<head>
   
</head>
<body>
<div class="container">
	<br>
	<br>
	<br>
	<div class="row col-1 container">
		<div class="col-md-12">
			<h4>Add Product</h4>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-primary">submit</button>

				


			</form>
				
		</div>
		<br>


	</div>
</div>
</body>
</html>

{% endblock %}

posproject/templates/product/productdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="row col-1">
	<div class="col-md-12">
		<form method="post">
			{% csrf_token %}
			<h4>Are you sure you want to delete?</h4>
			<button class="btn btn-danger">Delete</button>



			

		</form>
			

		

	</div>
	


</div>
<br>
{% endblock %}

posproject/templates/product/productlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}

	<div class="row">
		<div class="col-md-12 table-responsive-sm">
            <br>
			<a href="{% url 'posapp:productcreate' %}" class="btn btn-info"><i class="fa fa-plus"></i></a>
            <br>
			<table class="table table-bordered">
				<thead style="background-color: yellow;color:black;">
					<tr class="text-dark">
						<th>S.N</th>
						<th>Supplier</th>
						<th>productname</th>
						<th>Brand</th>
                        <th>price</th>
						<th>action</th>
                        
				
					</tr>	

				</thead>
				<tbody>
					{% for product in products %}
					<tr style="color: black;">
						<td>{{ forloop.counter }}</td>
						<td>{{ product.supplier.name }}</td>
						<td>{{ product.name }}</td>
						<td>{{ product.brand_name }}</td>
                        <td>{{ product.price }}</td>
                        
					
						<td>
                            <a href="{% url 'posapp:productupdate' product.pk %}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
							<a href="{% url 'posapp:productdelete' product.pk %}" class="btn btn-success"><i class="fa fa-trash"></i></a>

						</td>

					</tr>	


					{% endfor %}
				</tbody>
					
			</table>
		</div>
	</div>
{% endblock %}

posproject/templates/product/productupdate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="container">
    <br>
	<br>
    
	<div class="row col-1 container">
		<div class="col-md-12">
			<h4><u>Update Product</u></h4>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-primary">submit</button>

				


			</form>
				
		</div>
		<br>


	</div>
</div>

{% endblock %}